name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v1
        with:
          registry: registry.jellyfix.net
          username: ${{ secrets.REGISTRY_USERNAME  }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push the Docker image
        run: |
          docker build scraper --file Dockerfile -t registry.jellyfix.net/gorothprime/readarr-metadata-scraper:latest -t registry.jellyfix.net/gorothprime/readarr-metadata-scraper:${{ github.sha }}
          docker push registry.jellyfix.net/gorothprime/readarr-metadata-scraper:${{ github.sha }}
          docker push registry.jellyfix.net/gorothprime/readarr-metadata-scraper:latest
